### ISSUE TITLE
Warn should return error object

### ISSUE THREAD

**Issue by dominicwilliams** [mgutz/logxi#11]
Hey first of all I absolutely love logxi & feel bad about posting this first "issue" that is really a feature request!

Request: can we have Warn()  return the first error param like Error() does.

Reasoning by real example:-

I have a function that unpacks a packet received from the network, and analyzes its fields to make sure they are all legal in relation to the protocol and state transitions they will drive. In some circumstances, the packet will be illegal in the sense that it breaks a sequence of transitions, or something like that, and thus the function returns a predefined error describing what has happened, and higher level code resets the protocol. In this case the protocol is an overlay over and existing P2P network and such conditions are triggered quite naturally by various things and so resetting the virtual connection is quite normal and only merits a warning in the logs.  Nonetheless, I still want to pass up the error so the protocol can be reset.

Would there be any probs with having Warn return errors in the same way?

Best, Dominic

**Comment by mgutz** [comment]
You're the second person to suggest it. I'll look closer tomorrow to see if there is any performance impact. If not, I'll add it.

**Comment by mgutz** [comment]
Is this what you expect? If a warning entry has an error, return the error

```
// returns error
return logger.Warn("has an error", "err", error)
```

If a warning entry DOES NOT have an `error` it should return `nil`

```
// returns nil
return logger.Warn("plain warning", "key", value) 
```

**Comment by mgutz** [comment]
Please try and test branch `issue-11`

**Comment by dominicwilliams** [comment]
Yes, that works great, thanks.

**Comment by mgutz** [comment]
I'll leave this open for a bit to ensure stability. Will integrate in a week or so.
