### ISSUE TITLE
Feature: option to honor Stringer interface

### ISSUE THREAD

**Issue by ansel1** [mgutz/logxi#13]
If I have a large struct, logxi's map rendering of it can be too verbose.  I can implement String() on it, but logxi ignores it.  If I pass s.String() as the arg to logxi, I incur the Sprintf cost even when the log message is ignored, so I need to do this:

    if log.isTrace() { log.Trace("the struct", s.String())}

Would be cool if logxi had a flag to enable using String() if implemented.

**Comment by mgutz** [comment]
Agree. Kind of busy. Will try to sometime next week.
