### ISSUE TITLE
Option to disable colors

### ISSUE THREAD

**Issue by rgl** [mgutz/logxi#14]
When running under LiteIDE the colors make it really hard to read the program output (the LiteIDE terminal does not handle the ANSI escape sequences, as such, we see them intermingled with the actual program output).

Can we have an option to disable the colors? maybe LOGXI_COLORS=disable

**Comment by Omie** [comment]
Came here to ask exactly this, did some digging in code and turns out `LOGXI_COLORS=*=white` should do the job

**Comment by rgl** [comment]
@Omie no it doesn't. one still gets things like `[37m2015-09-13T17:40:31+0100[0m [37mINF[0m [37m~[0m`

**Comment by Omie** [comment]
ah, right. That needs some workaround, may be pretty-text

**Comment by mgutz** [comment]
I'll put in a fix this week

**Comment by mgutz** [comment]
Fixed by updating the ansi library used by logxi

```
go get -u github.com/mgutz/logxi/v1
```

Then using `off`

```
LOGXI_COLORS=*=off yourapp
```

Note, that in production colors are never used

**Comment by rgl** [comment]
@mgutz humm I'm still getting ansi codes (a lot less thou):

```
2015-09-15T08:37:47+0100[0m INF ~ SQLite version: [0m3.8.5
   sourceId: [0m2014-06-04 14:06:34 b1ed4f2a34ba66c29b130f8d13e9092758019212
```

**Comment by mgutz** [comment]
those zeros are the ansi reset sequence, please update and try again

**Comment by rgl** [comment]
looks good!
