### ISSUE TITLE
Using HappyDevFormatter can cause race conditions not present in the jsonFormatter

### ISSUE THREAD

**Issue by karlmutch** [mgutz/logxi#36]
No explicit statements are made concerning goroutine safety around this package.

Generally the package does appear to be safe except for the col variable inside the HappyDevFormat struct which when the format is called concurrently can lead to failures coming from the GoLang race detector.

**Comment by mgutz** [comment]
addressed in upcoming v2

**Comment by torbjornvatn** [comment]
When is the v2 due. I'm getting some Data race errors when running my tests with `--race`
