### ISSUE TITLE
Use of isTerminal before initialization

### ISSUE THREAD

**Issue by oblitum** [mgutz/logxi#6]
At line [init.go#L190](https://github.com/mgutz/logxi/blob/master/v1/init.go#L190) it seems like `isTerminal` is being checked before it's initialized at line [init.go#L197](https://github.com/mgutz/logxi/blob/master/v1/init.go#L197). This would make the internal logger to log always using json.

**Comment by mgutz** [comment]
I'll have a look tonight. Thanks again.

**Comment by oblitum** [comment]
@mgutz ok, by the way, this is offtopic but simple, there's a typo in the README you may fix in a future commit: "Higlights".
